### ISSUE TITLE
Update the current UI

### ISSUE THREAD

**Issue by hassan-mehedi** [UNI-Three/Blog#8]
# Tasks: 
---

## Check the doc for more specific information: 

- [x] Update the navbar
- [x] Update the home page
- [x] Change the layout of the blogs view
- [x] Create two more views, one of category option and another for content option
- [x] Create log in and sign up page
